# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: './TheZachZone.sln'
  tzzProjectDir: './APIs/TZZ.API'
  tgzProjectDir: './APIs/TGZ.API'
  tzzProject: '$(tzzProjectDir)/TZZ.API.csproj'
  tgzProject: '$(tgzProjectDir)/TGZ.API.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
  - task: NuGetToolInstaller@1

  - task: DotNetCoreCLI@2
    displayName: NuGet Restore
    inputs:
      command: 'restore'
      projects: '$(solution)'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: Build Solution
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--no-restore'
      configuration: $buildConfiguration

  - task: DotNetCoreCLI@2
    displayName: Publish TheZachZone
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '$(tzzProject)'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/TZZ --no-build'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'TZZ'
      publishLocation: 'Container'