global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  - job_name: "The Zach Zone"
    scheme: https
    tls_config:
        insecure_skip_verify: true
    static_configs:
      - targets: ["host.docker.internal:8001"]
  
  - job_name: "The Game Zone"
    scheme: https
    tls_config:
        insecure_skip_verify: true
    static_configs:
      - targets: ["host.docker.internal:8011"]
  
  - job_name: "PocketPersona"
    scheme: https
    tls_config:
        insecure_skip_verify: true
    static_configs:
      - targets: ["host.docker.internal:8021"]
  
  - job_name: "Node"
    static_configs:
      - targets: ["localhost:9100"]